export const newUserConst = [
  {
    name: "name",
    label: "Name",
    dataKey: "name",
    type: "text",
    isRequired: true,
    requiredErrorMessage: "Please enter your name.",
  },
  {
    name: "phoneNumber",
    label: "Phone Number",
    dataKey: "PhoneNumber",
    type: "text",
    isRequired: true,
    requiredErrorMessage: "Please enter your phone number.",
  },
  {
    name: "address",
    label: "Address",
    dataKey: "address",
    type: "text",
    isRequired: true,
    requiredErrorMessage: "Please enter your address.",
  },
  {
    name: "email",
    label: "Email",
    dataKey: "email",
    type: "email",
    isRequired: true,
    requiredErrorMessage: "Please enter your email.",
  },
  {
    name: "password",
    label: "Password",
    type: "password",
    isRequired: true,
    requiredErrorMessage: "Please enter your password.",
  },
  {
    name: "confirmPassword",
    label: "Confirm Password",
    type: "password",
    isRequired: true,
    requiredErrorMessage: "Please confirm your password.",
  },
  {
    name: "role",
    label: "Role",
    dataKey: "role",
    type: "select",
    isRequired: true,
    options: [
      { value: "BuilderFloorAdmin", label: "Builder Floor Admin" },
      { value: "ChannelPartner", label: "Channel Partner" },
      { value: "PropertyDealer", label: "Property Dealer" },
    ],
    requiredErrorMessage: "Please select a role.",
  },
];
