import { TEXT } from "../utils/Const";

export const newUserConst = [
  {
    name: "name",
    label: "Name",
    dataKey: "name",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your name.",
  },
  {
    name: "phoneNumber",
    label: "Mobile Number",
    dataKey: "PhoneNumber",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your phone number.",
  },
  {
    name: "email",
    label: "Email",
    dataKey: "email",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your email.",
  },
  {
    name: "companyName",
    label: "Company Name",
    dataKey: "companyName",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your name.",
  },
  {
    name: "companyAddress",
    label: "Company Address",
    dataKey: "companyAddress",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your address.",
  },

  {
    name: "city",
    label: "city",
    dataKey: "city",
    type: "select",
    isRequired: true,
    requiredErrorMessage: "Please select a City.",
  },
  {
    name: "state",
    label: "state",
    dataKey: "state",
    type: "select",
    isRequired: true,
    requiredErrorMessage: "Please select a State.",
  },
  {
    name: "sectorNumber",
    label: "Locations Allowed",
    dataKey: "location",
    type: "select",
    isRequired: true,
    isMulti: true,
    requiredErrorMessage: "Please select a Locations.",
  },
];

export const editUserConst = [
  {
    name: "name",
    label: "Name",
    dataKey: "name",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your name.",
  },
  {
    name: "phoneNumber",
    label: "Mobile Number",
    dataKey: "PhoneNumber",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your phone number.",
  },
  {
    name: "email",
    label: "Email",
    dataKey: "email",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your email.",
  },
  {
    name: "companyName",
    label: "Company Name",
    dataKey: "companyName",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your name.",
  },
  {
    name: "companyAddress",
    label: "Company Address",
    dataKey: "companyAddress",
    type: TEXT,
    isRequired: true,
    requiredErrorMessage: "Please enter your address.",
  },

  {
    name: "city",
    label: "city",
    dataKey: "city",
    type: "select",
    isRequired: true,
    requiredErrorMessage: "Please select a City.",
  },
  {
    name: "state",
    label: "state",
    dataKey: "state",
    type: "select",
    isRequired: true,
    requiredErrorMessage: "Please select a State.",
  },
  {
    name: "sectorNumber",
    label: "Locations Allowed",
    dataKey: "location",
    type: "select",
    isRequired: true,
    requiredErrorMessage: "Please select a Locations.",
  },
  {
    name: "status",
    label: "Status",
    dataKey: "status",
    type: "select",
    isRequired: true,
    requiredErrorMessage: "Please select a Status.",
  },
];
